// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClZ-1FgHs-LZyvtodsQ4JNzRmwJxlAgf8',
    appId: '1:838229134141:android:11c749b13dfc9053d5d354',
    messagingSenderId: '838229134141',
    projectId: 'notes-app-flutter-a0c95',
    storageBucket: 'notes-app-flutter-a0c95.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgBRbzyUp_wOArPvN7Mulg_g4rEjQU9zM',
    appId: '1:838229134141:ios:a7163643253b056cd5d354',
    messagingSenderId: '838229134141',
    projectId: 'notes-app-flutter-a0c95',
    storageBucket: 'notes-app-flutter-a0c95.appspot.com',
    iosClientId: '838229134141-vsdb95ste1ogqpe5idfagi7g92se1el8.apps.googleusercontent.com',
    iosBundleId: 'com.example.notesAppFlutter',
  );
}
